apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/cinqtechnologies/ninjabelt-rs:{{.VERSION}}"
  artifacts:
  - imageName: ninjabelt-rs
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: local
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/cinqtechnologies/ninjabelt-rs:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: ninjabelt-rs
        chartPath: charts/ninjabelt-rs
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/cinqtechnologies/ninjabelt-rs"
          image.tag: "{{.DIGEST_HEX}}"
